import pickle
import networkx as nx
from pyvis.network import Network

# =========================
# LOAD GRAPH
# =========================
DB_FOLDER = "db"    

print("Loading graph...")

with open(f"{DB_FOLDER}/graph.pkl", "rb") as f:
    G = pickle.load(f)

print(f"Graph loaded!")
print(f"Nodes: {len(G.nodes)}")
print(f"Edges: {len(G.edges)}")

# =========================
# CREATE PYVIS NETWORK
# =========================
net = Network(
    height="750px",
    width="100%",
    bgcolor="#111111",
    font_color="white",
    notebook=False
)

# =========================
# PHYSICS SETTINGS
# =========================
net.barnes_hut()

# =========================
# ADD NODES
# =========================
print("Adding nodes...")

for node in G.nodes():

    net.add_node(
        node,
        label=node,
        title=node,
        size=15
    )

# =========================
# ADD EDGES
# =========================
print("Adding edges...")

for source, target in G.edges():

    net.add_edge(
        source,
        target
    )

# =========================
# SAVE GRAPH & POST-PROCESS WITH PREMIUM LIGHT THEME
# =========================
OUTPUT_FILE = "graph.html"

print("Generating visualization...")
net.save_graph(OUTPUT_FILE)

def post_process_html(file_path):
    import re
    print("Post-processing HTML to apply premium light theme styling...")
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()

        # Locate the nodes and edges JSON data generated by PyVis
        nodes_match = re.search(r"nodes\s*=\s*new\s*vis\.DataSet\((.*?)\);", content)
        edges_match = re.search(r"edges\s*=\s*new\s*vis\.DataSet\((.*?)\);", content)

        if not nodes_match or not edges_match:
            print("Warning: Could not locate vis.DataSet in generated HTML!")
            return

        nodes_json = nodes_match.group(1)
        edges_json = edges_match.group(1)

        # Generate a premium, presentation-ready light mode dashboard
        premium_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Semantic RAG - Knowledge Graph Explorer</title>
    
    <!-- vis-network library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.2/dist/dist/vis-network.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vis-network/9.1.2/dist/vis-network.min.js"></script>
    
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <!-- Premium Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=Space+Grotesk:wght@400;500;700&display=swap" rel="stylesheet">

    <style type="text/css">
        body {{
            background-color: #f1f5f9;
            font-family: 'Outfit', sans-serif;
            color: #0f172a;
            padding: 24px;
            margin: 0;
            min-height: 100vh;
        }}
        
        .container-fluid {{
            max-width: 1600px;
        }}

        .dashboard-header {{
            margin-bottom: 20px;
        }}

        .card-container {{
            width: 100%;
            border-radius: 20px;
            overflow: hidden;
            background: #ffffff;
            box-shadow: 0 10px 30px -5px rgba(15, 23, 42, 0.05);
            border: 1px solid rgba(15, 23, 42, 0.05);
            position: relative;
        }}

        #mynetwork {{
            width: 100%;
            height: 760px;
            background-color: #f8fafc;
            background-image: radial-gradient(#cbd5e1 1.2px, transparent 1.2px);
            background-size: 24px 24px;
            position: relative;
        }}

        /* Floating Sidebar Explorer */
        .explorer-sidebar {{
            position: absolute;
            top: 20px;
            left: 20px;
            width: 350px;
            max-height: calc(100% - 40px);
            background: rgba(255, 255, 255, 0.90);
            backdrop-filter: blur(16px);
            -webkit-backdrop-filter: blur(16px);
            border: 1px solid rgba(15, 23, 42, 0.08);
            border-radius: 16px;
            padding: 24px;
            box-shadow: 0 20px 25px -5px rgba(15, 23, 42, 0.05), 0 8px 10px -6px rgba(15, 23, 42, 0.05);
            z-index: 10;
            display: flex;
            flex-direction: column;
            gap: 20px;
            overflow-y: auto;
            transition: all 0.3s ease;
        }}

        .brand-header {{
            display: flex;
            align-items: center;
            gap: 12px;
        }}
        
        .logo-icon {{
            font-size: 1.8rem;
            background: linear-gradient(135deg, #3b82f6, #1d4ed8);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }}

        .section-label {{
            font-size: 0.75rem;
            font-weight: 700;
            color: #64748b;
            text-transform: uppercase;
            letter-spacing: 0.07em;
            margin-bottom: 8px;
        }}

        /* Search Styles */
        .custom-search {{
            font-size: 0.9rem;
            border-radius: 10px;
            border: 1.5px solid #cbd5e1;
            padding: 10px 14px;
            background: #ffffff;
            transition: all 0.2s ease;
        }}

        .custom-search:focus {{
            border-color: #2563eb;
            box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.15);
            outline: none;
        }}

        .autocomplete-suggestions {{
            position: absolute;
            top: 100%;
            left: 0;
            right: 0;
            background: #ffffff;
            border: 1px solid #e2e8f0;
            border-radius: 10px;
            max-height: 220px;
            overflow-y: auto;
            z-index: 100;
            box-shadow: 0 10px 25px -5px rgba(15, 23, 42, 0.1);
            margin-top: 5px;
        }}

        .autocomplete-suggestion {{
            padding: 10px 14px;
            cursor: pointer;
            font-size: 0.85rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 1px solid #f1f5f9;
            transition: background 0.15s ease;
        }}

        .autocomplete-suggestion:hover {{
            background: #f8fafc;
        }}

        .autocomplete-suggestion:last-child {{
            border-bottom: none;
        }}

        /* Stats Styles */
        .stat-card {{
            background: rgba(15, 23, 42, 0.02);
            border: 1px solid rgba(15, 23, 42, 0.05);
            border-radius: 10px;
            padding: 10px 14px;
            text-align: center;
            transition: all 0.2s ease;
        }}

        .stat-card:hover {{
            background: rgba(15, 23, 42, 0.04);
            border-color: rgba(15, 23, 42, 0.08);
        }}

        .stat-val {{
            font-size: 1.4rem;
            font-weight: 700;
            color: #0f172a;
            font-family: 'Space Grotesk', sans-serif;
            line-height: 1.2;
        }}

        .stat-lbl {{
            font-size: 0.65rem;
            color: #64748b;
            font-weight: 700;
            text-transform: uppercase;
            margin-top: 4px;
        }}

        /* Node Inspector Styles */
        .inspector-card {{
            background: rgba(37, 99, 235, 0.03);
            border: 1px solid rgba(37, 99, 235, 0.08);
            border-radius: 12px;
            padding: 16px;
            animation: fadeIn 0.25s ease-out;
        }}

        @keyframes fadeIn {{
            from {{ opacity: 0; transform: translateY(5px); }}
            to {{ opacity: 1; transform: translateY(0); }}
        }}

        #inspector-name {{
            font-family: 'Space Grotesk', sans-serif;
            font-size: 1.15rem;
            font-weight: 700;
            color: #0f172a;
            word-break: break-word;
            line-height: 1.3;
        }}

        .neighbor-badge {{
            font-size: 0.75rem;
            padding: 5px 10px;
            border-radius: 8px;
            background: #ffffff;
            color: #475569;
            cursor: pointer;
            font-weight: 500;
            border: 1px solid #e2e8f0;
            transition: all 0.2s ease;
            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.02);
            margin: 2px;
            display: inline-block;
        }}

        .neighbor-badge:hover {{
            background: #cbd5e1;
            color: #0f172a;
            border-color: #94a3b8;
        }}

        /* Legend Styles */
        .legend-dot {{
            display: inline-block;
            width: 12px;
            height: 12px;
            border-radius: 50%;
        }}

        .legend-text {{
            color: #475569;
            font-weight: 500;
            font-size: 0.85rem;
        }}

        /* Custom Scrollbar for Sidebar */
        .explorer-sidebar::-webkit-scrollbar {{
            width: 6px;
        }}

        .explorer-sidebar::-webkit-scrollbar-track {{
            background: transparent;
        }}

        .explorer-sidebar::-webkit-scrollbar-thumb {{
            background: rgba(15, 23, 42, 0.15);
            border-radius: 3px;
        }}

        .explorer-sidebar::-webkit-scrollbar-thumb:hover {{
            background: rgba(15, 23, 42, 0.3);
        }}
    </style>
</head>

<body>
    <div class="container-fluid">
        <!-- Dashboard Header -->
        <div class="row dashboard-header">
            <div class="col-12 d-flex justify-content-between align-items-center">
                <div>
                    <h1 style="font-family: 'Space Grotesk', sans-serif; font-size: 1.75rem; font-weight: 700; margin: 0; color: #0f172a; letter-spacing: -0.02em;">Knowledge Graph Explorer</h1>
                    <p style="margin: 0; color: #64748b; font-size: 0.95rem; font-weight: 500;">High-Contrast Premium Blueprint Theme • Document Ready</p>
                </div>
                <div class="text-end">
                    <span class="badge bg-white text-dark shadow-sm border px-3 py-2" style="font-size: 0.85rem; font-weight: 600; border-radius: 30px;">
                        🟢 Database Connected
                    </span>
                </div>
            </div>
        </div>

        <!-- Main Card Wrapper -->
        <div class="row">
            <div class="col-12">
                <div class="card-container">
                    <!-- Floating Sidebar -->
                    <div class="explorer-sidebar">
                        <!-- Brand/Header -->
                        <div class="brand-header">
                            <span class="logo-icon">🧠</span>
                            <div>
                                <h2 style="font-family: 'Space Grotesk', sans-serif; font-size: 1.1rem; font-weight: 700; margin: 0; color: #0f172a;">Semantic RAG</h2>
                                <p style="font-size: 0.75rem; color: #64748b; font-weight: 600; margin: 0; text-transform: uppercase; letter-spacing: 0.05em;">Graph Explorer</p>
                            </div>
                        </div>

                        <hr class="my-1" style="border-color: rgba(15, 23, 42, 0.08);">

                        <!-- Search Section -->
                        <div>
                            <div class="section-label">Search Entities</div>
                            <div class="position-relative">
                                <input type="text" id="search-input" placeholder="Search concept or index..." class="form-control custom-search">
                                <div id="autocomplete-list" class="autocomplete-suggestions" style="display: none;"></div>
                            </div>
                        </div>

                        <!-- Statistics Section -->
                        <div>
                            <div class="section-label">Graph Statistics</div>
                            <div class="row g-2">
                                <div class="col-6">
                                    <div class="stat-card">
                                        <div class="stat-val" id="stat-nodes-val">0</div>
                                        <div class="stat-lbl">Entities</div>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="stat-card">
                                        <div class="stat-val" id="stat-edges-val">0</div>
                                        <div class="stat-lbl">Relations</div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Entity Inspector (Hidden by Default) -->
                        <div id="inspector-section" style="display: none;">
                            <div class="section-label">Entity Details</div>
                            <div class="inspector-card">
                                <div class="d-flex justify-content-between align-items-start mb-2">
                                    <h3 id="inspector-name">Concept Name</h3>
                                    <span class="badge" id="inspector-badge" style="font-size: 0.75rem; padding: 4px 8px; border-radius: 6px;">Concept</span>
                                </div>
                                <div class="mb-1" style="font-size: 0.75rem; font-weight: 700; color: #64748b; text-transform: uppercase;">Connected Entities</div>
                                <div class="d-flex flex-wrap gap-1 mt-1.5" id="inspector-neighbors">
                                    <!-- Dynamic neighbor badges -->
                                </div>
                            </div>
                        </div>

                        <!-- Legend Section -->
                        <div>
                            <div class="section-label">Legend & Types</div>
                            <div class="d-flex flex-column gap-2.5">
                                <div class="d-flex align-items-center gap-2.5">
                                    <span class="legend-dot" style="background: #bfdbfe; border: 2.5px solid #1d4ed8;"></span>
                                    <span class="legend-text">Semantic Concepts (Concepts)</span>
                                </div>
                                <div class="d-flex align-items-center gap-2.5">
                                    <span class="legend-dot" style="background: #e2e8f0; border: 2px solid #64748b;"></span>
                                    <span class="legend-text">Source Documents (Indices)</span>
                                </div>
                            </div>
                        </div>

                        <!-- Controls Section -->
                        <div class="d-flex gap-2">
                            <button class="btn btn-outline-primary btn-sm flex-grow-1 py-2" id="btn-fit" style="border-radius: 10px; font-weight: 600; font-size: 0.85rem;">
                                🔍 Fit Viewport
                            </button>
                            <button class="btn btn-outline-secondary btn-sm px-3 py-2" id="btn-physics" style="border-radius: 10px; font-weight: 600; font-size: 0.85rem;" title="Pause / Resume Physics Simulation">
                                ⏸️ Physics
                            </button>
                        </div>
                    </div>

                    <!-- Main Network Div -->
                    <div id="mynetwork"></div>
                </div>
            </div>
        </div>
    </div>

    <!-- Vis.js Initializer & Interactive Logic -->
    <script type="text/javascript">
        var container = document.getElementById('mynetwork');
        
        // Parse raw datasets from python
        var rawNodes = {nodes_json};
        var rawEdges = {edges_json};

        // Create standard dataset wrappers
        var nodes = new vis.DataSet();
        var edges = new vis.DataSet();

        // 🎨 Transform nodes & apply premium light-theme colors dynamically
        rawNodes.forEach(function(node) {{
            // Concept nodes are non-numeric IDs, Index nodes are numeric IDs
            var isConcept = isNaN(node.id);
            if (isConcept) {{
                nodes.add({{
                    id: node.id,
                    label: node.id,
                    title: node.id,
                    shape: 'dot',
                    size: 18,
                    borderWidth: 2.5,
                    color: {{
                        background: '#bfdbfe',
                        border: '#1d4ed8',
                        highlight: {{
                            background: '#93c5fd',
                            border: '#1e40af'
                        }},
                        hover: {{
                            background: '#93c5fd',
                            border: '#1e40af'
                        }}
                    }},
                    font: {{
                        color: '#0f172a',
                        size: 15,
                        face: 'Outfit',
                        strokeWidth: 3,
                        strokeColor: '#ffffff',
                        bold: true
                    }},
                    shadow: {{
                        enabled: true,
                        color: 'rgba(15, 23, 42, 0.06)',
                        size: 8,
                        x: 0,
                        y: 3
                    }}
                }});
            }} else {{
                nodes.add({{
                    id: node.id,
                    label: node.id,
                    title: 'Document ID: ' + node.id,
                    shape: 'dot',
                    size: 14,
                    borderWidth: 2,
                    color: {{
                        background: '#e2e8f0',
                        border: '#64748b',
                        highlight: {{
                            background: '#cbd5e1',
                            border: '#475569'
                        }},
                        hover: {{
                            background: '#cbd5e1',
                            border: '#475569'
                        }}
                    }},
                    font: {{
                        color: '#334155',
                        size: 13,
                        face: 'Outfit',
                        strokeWidth: 3,
                        strokeColor: '#ffffff',
                        bold: true
                    }},
                    shadow: {{
                        enabled: true,
                        color: 'rgba(15, 23, 42, 0.04)',
                        size: 6,
                        x: 0,
                        y: 2
                    }}
                }});
            }}
        }});

        // Add raw edges & apply presentation styling (thicker, high-visibility)
        rawEdges.forEach(function(edge) {{
            edges.add({{
                from: edge.from,
                to: edge.to,
                width: 3.5, // Bold high-visibility thickness for screenshot readability
                color: {{
                    color: '#94a3b8',
                    highlight: '#1d4ed8',
                    hover: '#1d4ed8',
                    inherit: false
                }},
                smooth: {{
                    enabled: true,
                    type: 'cubicBezier',
                    roundness: 0.5
                }}
            }});
        }});

        // Set up statistics in sidebar
        document.getElementById('stat-nodes-val').innerText = nodes.length;
        document.getElementById('stat-edges-val').innerText = edges.length;

        var data = {{ nodes: nodes, edges: edges }};

        // Layout Options
        var options = {{
            interaction: {{
                hover: true,
                dragNodes: true,
                hideEdgesOnDrag: false,
                hideNodesOnDrag: false
            }},
            physics: {{
                enabled: true,
                barnesHut: {{
                    gravitationalConstant: -25000,
                    centralGravity: 0.3,
                    springLength: 200,
                    springConstant: 0.005,
                    damping: 0.09,
                    avoidOverlap: 1.0
                }},
                stabilization: {{
                    enabled: true,
                    fit: true,
                    iterations: 600,
                    updateInterval: 50
                }}
            }}
        }};

        // Initialize Vis.js Network
        var network = new vis.Network(container, data, options);

        // ==========================================
        // DYNAMIC INTERACTION: SEARCH & AUTOCOMPLETE
        // ==========================================
        var searchInput = document.getElementById('search-input');
        var autocompleteList = document.getElementById('autocomplete-list');

        searchInput.addEventListener('input', function() {{
            var query = this.value.toLowerCase().trim();
            autocompleteList.innerHTML = '';
            
            if (query.length === 0) {{
                autocompleteList.style.display = 'none';
                return;
            }}

            var matchedNodes = nodes.get({{
                filter: function(item) {{
                    return item.label.toLowerCase().indexOf(query) !== -1;
                }}
            }});

            if (matchedNodes.length === 0) {{
                autocompleteList.style.display = 'none';
                return;
            }}

            autocompleteList.style.display = 'block';
            matchedNodes.slice(0, 5).forEach(function(node) {{
                var isConcept = isNaN(node.id);
                var badgeClass = isConcept ? 'bg-primary' : 'bg-secondary';
                var typeLabel = isConcept ? 'Concept' : 'Doc';

                var row = document.createElement('div');
                row.className = 'autocomplete-suggestion';
                row.innerHTML = '<span>' + node.label + '</span><span class="badge ' + badgeClass + '">' + typeLabel + '</span>';
                
                row.addEventListener('click', function() {{
                    searchInput.value = node.label;
                    autocompleteList.style.display = 'none';
                    highlightNode(node.id);
                }});
                
                autocompleteList.appendChild(row);
            }});
        }});

        // Hide autocomplete when clicking outside
        document.addEventListener('click', function(e) {{
            if (e.target !== searchInput && e.target !== autocompleteList) {{
                autocompleteList.style.display = 'none';
            }}
        }});

        // ==========================================
        // DYNAMIC INTERACTION: INSPECTOR
        // ==========================================
        var inspectorSection = document.getElementById('inspector-section');
        var inspectorName = document.getElementById('inspector-name');
        var inspectorBadge = document.getElementById('inspector-badge');
        var inspectorNeighbors = document.getElementById('inspector-neighbors');

        function highlightNode(nodeId) {{
            network.selectNodes([nodeId]);
            network.focus(nodeId, {{
                scale: 1.3,
                animation: {{
                    duration: 800,
                    easingFunction: 'easeInOutQuad'
                }}
            }});
            showNodeDetails(nodeId);
        }}

        function showNodeDetails(nodeId) {{
            var node = nodes.get(nodeId);
            if (!node) return;

            var isConcept = isNaN(nodeId);
            
            // Set details
            inspectorName.innerText = node.label;
            inspectorBadge.innerText = isConcept ? 'Semantic Concept' : 'Source Document';
            inspectorBadge.className = 'badge ' + (isConcept ? 'bg-primary' : 'bg-secondary');

            // Find neighbors
            var neighbors = network.getConnectedNodes(nodeId);
            inspectorNeighbors.innerHTML = '';
            
            if (neighbors.length === 0) {{
                inspectorNeighbors.innerHTML = '<span class="text-muted" style="font-size: 0.8rem;">No connections found</span>';
            }} else {{
                neighbors.forEach(function(nId) {{
                    var nNode = nodes.get(nId);
                    if (nNode) {{
                        var badge = document.createElement('span');
                        badge.className = 'neighbor-badge';
                        badge.innerText = nNode.label;
                        badge.addEventListener('click', function() {{
                            highlightNode(nId);
                        }});
                        inspectorNeighbors.appendChild(badge);
                    }}
                }});
            }}

            inspectorSection.style.display = 'block';
        }}

        function clearNodeDetails() {{
            inspectorSection.style.display = 'none';
        }}

        // Listen for Node Selection events
        network.on("selectNode", function(params) {{
            if (params.nodes.length > 0) {{
                showNodeDetails(params.nodes[0]);
            }}
        }});

        network.on("deselectNode", function(params) {{
            clearNodeDetails();
        }});

        // ==========================================
        // BUTTON CONTROLS
        // ==========================================
        document.getElementById('btn-fit').addEventListener('click', function() {{
            network.fit({{
                animation: {{
                    duration: 1000,
                    easingFunction: 'easeInOutQuad'
                }}
            }});
        }});

        var physicsEnabled = true;
        var btnPhysics = document.getElementById('btn-physics');
        btnPhysics.addEventListener('click', function() {{
            physicsEnabled = !physicsEnabled;
            network.setOptions({{ physics: {{ enabled: physicsEnabled }} }});
            btnPhysics.innerText = physicsEnabled ? '⏸️ Physics' : '▶️ Physics';
            btnPhysics.className = 'btn btn-sm px-3 py-2 ' + (physicsEnabled ? 'btn-outline-secondary' : 'btn-primary');
        }});
    </script>
</body>
</html>
"""
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(premium_html)
        print("Premium styling successfully post-processed and saved!")
    except Exception as e:
        print(f"Error post-processing HTML file: {e}")

post_process_html(OUTPUT_FILE)

print(f"\nGraph visualization saved as: {OUTPUT_FILE}")
print("Open graph.html in your browser.")